# This Python file uses the following encoding: utf-8
"""autogenerated by genpy from robottest/signal_robot.msg. Do not edit."""
import sys
python3 = True if sys.hexversion > 0x03000000 else False
import genpy
import struct

import geometry_msgs.msg

class signal_robot(genpy.Message):
  _md5sum = "7edb32daa132df4f0725a8b5753c4c95"
  _type = "robottest/signal_robot"
  _has_header = False #flag to mark the presence of a Header object
  _full_text = """float64               abratio      
int8                  detectcolor  
bool                  detect_done 
int8                  reportgoal
geometry_msgs/Pose2D   odometrie_1 
geometry_msgs/Pose2D   odometrie_2


================================================================================
MSG: geometry_msgs/Pose2D
# Deprecated
# Please use the full 3D pose.

# In general our recommendation is to use a full 3D representation of everything and for 2D specific applications make the appropriate projections into the plane for their calculations but optimally will preserve the 3D information during processing.

# If we have parallel copies of 2D datatypes every UI and other pipeline will end up needing to have dual interfaces to plot everything. And you will end up with not being able to use 3D tools for 2D use cases even if they're completely valid, as you'd have to reimplement it with different inputs and outputs. It's not particularly hard to plot the 2D pose or compute the yaw error for the Pose message and there are already tools and libraries that can do this for you.


# This expresses a position and orientation on a 2D manifold.

float64 x
float64 y
float64 theta
"""
  __slots__ = ['abratio','detectcolor','detect_done','reportgoal','odometrie_1','odometrie_2']
  _slot_types = ['float64','int8','bool','int8','geometry_msgs/Pose2D','geometry_msgs/Pose2D']

  def __init__(self, *args, **kwds):
    """
    Constructor. Any message fields that are implicitly/explicitly
    set to None will be assigned a default value. The recommend
    use is keyword arguments as this is more robust to future message
    changes.  You cannot mix in-order arguments and keyword arguments.

    The available fields are:
       abratio,detectcolor,detect_done,reportgoal,odometrie_1,odometrie_2

    :param args: complete set of field values, in .msg order
    :param kwds: use keyword arguments corresponding to message field names
    to set specific fields.
    """
    if args or kwds:
      super(signal_robot, self).__init__(*args, **kwds)
      #message fields cannot be None, assign default values for those that are
      if self.abratio is None:
        self.abratio = 0.
      if self.detectcolor is None:
        self.detectcolor = 0
      if self.detect_done is None:
        self.detect_done = False
      if self.reportgoal is None:
        self.reportgoal = 0
      if self.odometrie_1 is None:
        self.odometrie_1 = geometry_msgs.msg.Pose2D()
      if self.odometrie_2 is None:
        self.odometrie_2 = geometry_msgs.msg.Pose2D()
    else:
      self.abratio = 0.
      self.detectcolor = 0
      self.detect_done = False
      self.reportgoal = 0
      self.odometrie_1 = geometry_msgs.msg.Pose2D()
      self.odometrie_2 = geometry_msgs.msg.Pose2D()

  def _get_types(self):
    """
    internal API method
    """
    return self._slot_types

  def serialize(self, buff):
    """
    serialize message into buffer
    :param buff: buffer, ``StringIO``
    """
    try:
      _x = self
      buff.write(_get_struct_dbBb6d().pack(_x.abratio, _x.detectcolor, _x.detect_done, _x.reportgoal, _x.odometrie_1.x, _x.odometrie_1.y, _x.odometrie_1.theta, _x.odometrie_2.x, _x.odometrie_2.y, _x.odometrie_2.theta))
    except struct.error as se: self._check_types(struct.error("%s: '%s' when writing '%s'" % (type(se), str(se), str(locals().get('_x', self)))))
    except TypeError as te: self._check_types(ValueError("%s: '%s' when writing '%s'" % (type(te), str(te), str(locals().get('_x', self)))))

  def deserialize(self, str):
    """
    unpack serialized message in str into this message instance
    :param str: byte array of serialized message, ``str``
    """
    try:
      if self.odometrie_1 is None:
        self.odometrie_1 = geometry_msgs.msg.Pose2D()
      if self.odometrie_2 is None:
        self.odometrie_2 = geometry_msgs.msg.Pose2D()
      end = 0
      _x = self
      start = end
      end += 59
      (_x.abratio, _x.detectcolor, _x.detect_done, _x.reportgoal, _x.odometrie_1.x, _x.odometrie_1.y, _x.odometrie_1.theta, _x.odometrie_2.x, _x.odometrie_2.y, _x.odometrie_2.theta,) = _get_struct_dbBb6d().unpack(str[start:end])
      self.detect_done = bool(self.detect_done)
      return self
    except struct.error as e:
      raise genpy.DeserializationError(e) #most likely buffer underfill


  def serialize_numpy(self, buff, numpy):
    """
    serialize message with numpy array types into buffer
    :param buff: buffer, ``StringIO``
    :param numpy: numpy python module
    """
    try:
      _x = self
      buff.write(_get_struct_dbBb6d().pack(_x.abratio, _x.detectcolor, _x.detect_done, _x.reportgoal, _x.odometrie_1.x, _x.odometrie_1.y, _x.odometrie_1.theta, _x.odometrie_2.x, _x.odometrie_2.y, _x.odometrie_2.theta))
    except struct.error as se: self._check_types(struct.error("%s: '%s' when writing '%s'" % (type(se), str(se), str(locals().get('_x', self)))))
    except TypeError as te: self._check_types(ValueError("%s: '%s' when writing '%s'" % (type(te), str(te), str(locals().get('_x', self)))))

  def deserialize_numpy(self, str, numpy):
    """
    unpack serialized message in str into this message instance using numpy for array types
    :param str: byte array of serialized message, ``str``
    :param numpy: numpy python module
    """
    try:
      if self.odometrie_1 is None:
        self.odometrie_1 = geometry_msgs.msg.Pose2D()
      if self.odometrie_2 is None:
        self.odometrie_2 = geometry_msgs.msg.Pose2D()
      end = 0
      _x = self
      start = end
      end += 59
      (_x.abratio, _x.detectcolor, _x.detect_done, _x.reportgoal, _x.odometrie_1.x, _x.odometrie_1.y, _x.odometrie_1.theta, _x.odometrie_2.x, _x.odometrie_2.y, _x.odometrie_2.theta,) = _get_struct_dbBb6d().unpack(str[start:end])
      self.detect_done = bool(self.detect_done)
      return self
    except struct.error as e:
      raise genpy.DeserializationError(e) #most likely buffer underfill

_struct_I = genpy.struct_I
def _get_struct_I():
    global _struct_I
    return _struct_I
_struct_dbBb6d = None
def _get_struct_dbBb6d():
    global _struct_dbBb6d
    if _struct_dbBb6d is None:
        _struct_dbBb6d = struct.Struct("<dbBb6d")
    return _struct_dbBb6d
